os:
  - linux
  - osx

env:
  - CMAKE_PREFIX_PATH=/usr/local/opt/qt5

language: c
compiler:
  - gcc
  - clang

sudo: required

before_install:
  - ./.travis-deps.sh

script: mkdir build && cd build && cmake .. && make
